### ISSUE TITLE
load caffe model

### ISSUE THREAD

**Issue by kingvision** [bluuuuer/forward-caffe#1]
Hi
    if i load a pre-trained caffe model, how i should do? can you give me an example?
thanks

**Comment by bluuuuer** [comment]
This current version of forward-caffe is not complete. I have the complete version with both CPU & GPU mode that not updated yet. I'm busy doing another project. Plz wait, I'll update once done this project.
:)

**Comment by kingvision** [comment]
Hello, before you said you had don't rely on the third library forward version of CPU and GPU code, free updates now?
thank you
